---
title: "cleaning"
author: "JJayes"
date: "23/04/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(pacman)

p_load(tidyverse, readxl)
```

### Purpose

Cleaning and merging data on energy data from [BP](https://www.bp.com/en/global/corporate/energy-economics/statistical-review-of-world-energy.html)

* In this review, primary energy comprises commercially traded fuels, including modern renewables used to generate electricity. 


### Primary Energy Consumpton by Source. Reading in data

```{r}

df <- readxl::read_excel("data/test.xlsx")

df <- df %>% 
  filter(!is.na(entity),
         !str_detect(entity, "Total")) %>% 
  mutate(metric = "Primary energy: Consumption",
         unit = "exajoules") %>% 
  mutate(across(-c(entity, metric, unit), parse_number))

df <- df %>% 
  replace(is.na(.), 0) %>% 
  mutate(total = rowSums(across(where(is.numeric)))) %>% 
  arrange(desc(total)) %>% 
  mutate(largest_index = row_number()) %>% 
  pivot_longer(-c(entity, metric, total, largest_index, unit), names_to = "year") %>% 
  mutate(year = parse_number(year)) %>% 
  janitor::clean_names()

# df <- df %>% 
#   filter(!is.na(exajoules))

df %>%
  filter(largest_index <= 10) %>% 
  ggplot(aes(year, value, colour = entity)) +
  geom_line()


```


```{r}
df <- read_excel("data/primary-energy-consumption-by-fuel-2018-2019.xlsx")

df <- df %>% 
  filter(!is.na(entity),
         !str_detect(entity, "Total")) %>% 
  mutate(metric = "Primary energy: Consumption by fuel",
         unit = "exajoules") %>% 
  group_by(year) %>% 
  arrange(desc(Total)) %>% 
  mutate(largest_index = row_number()) %>% 
  ungroup()

df_pct <- df %>% 
  mutate(across(-c(entity, year, metric, unit, largest_index), ~ .x/Total))

df <- df %>% 
  pivot_longer(-c(entity, year, metric, unit, largest_index), names_to = "fuel")

df_pct <- df_pct %>% 
  pivot_longer(-c(entity, year, metric, unit, largest_index), names_to = "fuel")

df %>% 
  filter(year == 2019,
         largest_index <= 15,
         fuel != "Total") %>% 
  pivot_wider(names_from = "fuel") %>% 
  mutate(entity = fct_reorder(entity, `Renewables`)) %>% 
  pivot_longer(-c(entity, year, metric, unit, largest_index), names_to = "fuel") %>% 
  ggplot(aes(value, entity, fill = fuel)) +
  geom_col(position = "fill")

df_pct %>% 
  filter(year == 2019,
         largest_index <= 15,
         fuel != "Total") %>% 
  pivot_wider(names_from = "fuel") %>% 
  mutate(entity = fct_reorder(entity, `Renewables`)) %>% 
  pivot_longer(-c(entity, year, metric, unit, largest_index), names_to = "fuel") %>% 
  ggplot(aes(value, entity, fill = fuel)) +
  geom_col(position = "fill") +
  scale_x_continuous(labels = scales::percent_format()) +
  scale_fill_brewer(palette = "Dark2") +
  guides(fill = guide_legend(reverse = T)) +
  labs(x = "Share of primary energy from:",
       y = NULL,
       fill = "Fuel") 


```

